<?xml version="1.0" encoding="utf-8"?>
<knimeNode icon="catch.png" type="ScopeEnd" xmlns="http://knime.org/node/v2.8" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://knime.org/node/v2.8 http://knime.org/node/v2.8.xsd">
    <name>Catch Errors (DB Ports)</name>
    
    <shortDescription>End of Try-Catch construct. Use second input if execution leading to first input failed.</shortDescription>
    
    <fullDescription>
        <intro>
        This node forwards the input from the first port if the execution was
        successful. If execution on the top branch failed (and a matching try
        node was connected before the failing node!) then the input from the
        second port will be forwarded and the second variable outport will contain
        information about the observed error.
        </intro>
        <option name="Always populate error variables">If selected, the variables will also be generated when the node is not failing
        with the default values as selected.</option>
        <option name="Default for FailingNode variable:">Default value for the FailingNode variable, if no node is failing.</option>
        <option name="Default for FailingNodeMessage variable:">Default value for the FailingNodeMessage variable, if no node is failing.</option>
        <option name="Default for FailingNodeStackTrace variable:">Default value for the FailingNodeStackTrace variable, if no node is failing.</option>
    </fullDescription>
    
    <ports>
        <inPort index="0" name="Original input">The original input</inPort>
        <inPort index="1" name="Default input">The input to be used when execution on the main branch failed.</inPort>
        <outPort index="0" name="Output">Original input or default if execution failed.</outPort>
        <outPort index="1" name="Failure">Reasons for Failure (if any).</outPort>
    </ports>
</knimeNode>
